# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='title',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
