# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_accomplishments_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveIntegerField(blank=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='academicdetail',
            name='percentage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accomplishments',
            name='desciption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
