# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20170814_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('btec', 'B.TECH'), ('mtec', 'M.TECH'), ('tea', 'teacher'), ('rst', 'Reaserch Student')], max_length=4),
        ),
    ]
