# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20170814_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_code', models.CharField(max_length=50)),
                ('sub_name', models.CharField(max_length=100)),
                ('syllabus', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lab_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assig_number', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('assig_file', models.FileField(upload_to='')),
                ('sub_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture_notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppt_number', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('ppt_file', models.FileField(upload_to='')),
                ('sub_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tut_number', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('tut_file', models.FileField(upload_to='')),
                ('sub_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Course')),
            ],
        ),
    ]
