# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_course_lab_assignment_lecture_notes_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_year',
            field=models.CharField(choices=[('1st', '1st Year Student'), ('2nd', '2nd Year Student'), ('3rd', 'Third Year Student'), ('4th', '4th Year Student')], default='1st', max_length=3),
        ),
        migrations.AddField(
            model_name='course',
            name='user_type',
            field=models.CharField(choices=[('btec', 'B.TECH'), ('mtec', 'M.TECH'), ('tea', 'teacher'), ('rst', 'Reaserch Student')], default='null', max_length=4),
            preserve_default=False,
        ),
    ]
