# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_coursecordinator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecordinator',
            old_name='course',
            new_name='sub_code',
        ),
        migrations.RenameField(
            model_name='coursecordinator',
            old_name='user',
            new_name='user_corse_cord',
        ),
    ]
