# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20170818_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_cgpa',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
