# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0018_auto_20170819_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecordinator',
            name='sub_code',
        ),
        migrations.RemoveField(
            model_name='coursecordinator',
            name='user_corse_cord',
        ),
        migrations.AddField(
            model_name='course',
            name='corse_cord',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CourseCordinator',
        ),
    ]
