# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20170819_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='corse_cord',
            field=models.ManyToManyField(to='base.UserProfile'),
        ),
    ]
