# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0020_auto_20170819_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='corse_cord',
        ),
        migrations.AddField(
            model_name='course',
            name='corse_cord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
