# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_research_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='research_paper',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
