# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_research_paper_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Presents_material_in_a_variety_of_ways', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('S', 'Sometimes'), ('D', 'Dont Know')], max_length=4)),
                ('Teaches_in_a_way_that_I_can_understand', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('S', 'Sometimes'), ('D', 'Dont Know')], max_length=4)),
                ('Treats_all_students_with_respect', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('S', 'Sometimes'), ('D', 'Dont Know')], max_length=4)),
                ('Student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_stu', to='base.UserProfile')),
                ('Teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_tea', to='base.UserProfile')),
            ],
        ),
    ]
