# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 04:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20171003_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
