# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_feedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='comments',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
