# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_feedback_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='Teaches_in_a_way_that_I_can_understand',
        ),
        migrations.AddField(
            model_name='feedback',
            name='Taught_in_a_way_that_I_can_understand',
            field=models.CharField(choices=[('Yes', 'Y'), ('No', 'N'), ('Sometimes', 'S'), ('Dont Know', 'D')], default='null', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Presents_material_in_a_variety_of_ways',
            field=models.CharField(choices=[('Yes', 'Y'), ('No', 'N'), ('Sometimes', 'S'), ('Dont Know', 'D')], max_length=4),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Treats_all_students_with_respect',
            field=models.CharField(choices=[('Yes', 'Y'), ('No', 'N'), ('Sometimes', 'S'), ('Dont Know', 'D')], max_length=4),
        ),
    ]
