# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20171004_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='How_is_the_pace_of_the_class',
            field=models.CharField(choices=[('Fast', 'Fast'), ('Perfect', 'Perfect'), ('Slow', 'Slow')], default='Slow', max_length=10),
        ),
    ]
