# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_auto_20171004_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Were_notes_efficient_for_after_learning',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Sometimes', 'Sometimes'), ('NA', 'NA')], default='NA', max_length=10),
        ),
    ]
