# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20171007_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ifactor',
            field=models.IntegerField(default=6),
        ),
    ]
