# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_feedback_ifactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research_paper',
            name='year',
            field=models.DateField(),
        ),
    ]
