# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20171007_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research_paper',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
