# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20171007_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research_paper',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
